# Generated by Django 5.2.1 on 2025-06-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_type', models.CharField(help_text='Exact truck type name from spreadsheet', max_length=100, unique=True)),
                ('gw', models.IntegerField(help_text='Gross Weight in kg')),
                ('net_weight', models.IntegerField(help_text='Net Weight in kg')),
                ('avg_kmpl', models.DecimalField(decimal_places=2, help_text='Average KM per liter', max_digits=5)),
                ('driver_salary', models.DecimalField(decimal_places=2, help_text='Monthly driver salary', max_digits=10)),
                ('distance_traveled', models.IntegerField(help_text='Average monthly distance traveled in km')),
                ('en_route_expenses', models.DecimalField(decimal_places=2, default=2.0, help_text='En-route expenses per km', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Truck Specification',
                'verbose_name_plural': 'Truck Specifications',
                'ordering': ['truck_type'],
            },
        ),
    ]
